---
language: node_js
node_js:
  - "8"

sudo: false
cache: yarn

matrix:
  fast_finish: true

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH

install:
  - yarn install

script:
  - yarn test:node && ember try:each
